### ISSUE TITLE
Inferred Row/Col alignment feature

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#453]
It looks like the `infer=True` parameter of `get_col_ngrams` and `get_row_ngrams` isn't behaving quite as expected.

Given the following html table:

![image](https://cloud.githubusercontent.com/assets/7573542/19018900/effa7d6a-8826-11e6-8443-b04f46d2f73a.png)

```html
    <table>
        <tbody>
            <tr>
                <th>Problem</th>
                <th>Cause</th>
                <th>Cost</th>
            </tr>
            <tr>
                <th>BC546</th>
                <td></td>
                <td>K/W</td>
            </tr>
            <tr>
                <th>Storage Temperature</th>
                <td>-55</td>
                <td></td>
            </tr>
            <tr>
                <th>Hypochondria</th>
                <td>Fear</td>
                <td>$100</td>
            </tr>
        </tbody>
        <caption>
            Table 2: Three ways to get Pneumonia and how much they cost.
        </caption>
    </table>
```

When we look for Part-Temperature candidates as is done in the table tuturials, we find 1 candidate (BC546, -55).

However, looking at the features with `infer=False`, we have:
```
AnnotationKey (TAB_e1_WORD_SEQ_[BC546])
AnnotationKey (TAB_e1_LEMMA_SEQ_[bc546])
AnnotationKey (TAB_e1_POS_SEQ_[NN])
AnnotationKey (TAB_e1_DEP_SEQ_[ROOT])
AnnotationKey (TAB_e1_W_LEFT_1_[bc546])
AnnotationKey (TAB_e1_W_LEFT_POS_1_[NN])
AnnotationKey (TAB_e1_STARTS_WITH_CAPITAL)
AnnotationKey (TAB_e1_LENGTH_1)
AnnotationKey (TAB_e1_HTML_TAG_th)
AnnotationKey (TAB_e1_HTML_ANC_TAG_[html])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[body])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[table])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[tbody])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[tr])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[th])
AnnotationKey (TAB_e1_ROW_NUM_[1])
AnnotationKey (TAB_e1_COL_NUM_[0])
AnnotationKey (TAB_e1_ROW_WORDS_[bc546])
AnnotationKey (TAB_e1_ROW_WORDS_[k/w])
AnnotationKey (TAB_e1_COL_WORDS_[problem])
AnnotationKey (TAB_e1_COL_WORDS_[bc546])
AnnotationKey (TAB_e1_COL_WORDS_[storage])
AnnotationKey (TAB_e1_COL_WORDS_[storage temperature])
AnnotationKey (TAB_e1_COL_WORDS_[temperature])
AnnotationKey (TAB_e1_COL_WORDS_[hypochondria])
AnnotationKey (TAB_e2_WORD_SEQ_[-55])
AnnotationKey (TAB_e2_LEMMA_SEQ_[-55])
AnnotationKey (TAB_e2_POS_SEQ_[CD])
AnnotationKey (TAB_e2_DEP_SEQ_[ROOT])
AnnotationKey (TAB_e2_W_LEFT_1_[_NUMBER])
AnnotationKey (TAB_e2_W_LEFT_POS_1_[CD])
AnnotationKey (TAB_e2_LENGTH_1)
AnnotationKey (TAB_e2_HTML_TAG_td)
AnnotationKey (TAB_e2_HTML_ANC_TAG_[html])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[body])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[table])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[tbody])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[tr])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[td])
AnnotationKey (TAB_e2_ROW_NUM_[2])
AnnotationKey (TAB_e2_COL_NUM_[1])
AnnotationKey (TAB_e2_ROW_WORDS_[storage])
AnnotationKey (TAB_e2_ROW_WORDS_[storage temperature])
AnnotationKey (TAB_e2_ROW_WORDS_[temperature])
AnnotationKey (TAB_e2_ROW_WORDS_[-55])
AnnotationKey (TAB_e2_COL_WORDS_[cause])
AnnotationKey (TAB_e2_COL_WORDS_[-55])
AnnotationKey (TAB_e2_COL_WORDS_[fear])
AnnotationKey (TAB_SAME_TABLE)
AnnotationKey (TAB_SAME_TABLE_ROW_DIFF_[-1])
AnnotationKey (TAB_SAME_TABLE_COL_DIFF_[-1])
AnnotationKey (TAB_SAME_TABLE_MANHATTAN_DIST_[2])
```

With `infer=True` we have:
```
AnnotationKey (TAB_e1_WORD_SEQ_[BC546])
AnnotationKey (TAB_e1_LEMMA_SEQ_[bc546])
AnnotationKey (TAB_e1_POS_SEQ_[NN])
AnnotationKey (TAB_e1_DEP_SEQ_[ROOT])
AnnotationKey (TAB_e1_W_LEFT_1_[bc546])
AnnotationKey (TAB_e1_W_LEFT_POS_1_[NN])
AnnotationKey (TAB_e1_STARTS_WITH_CAPITAL)
AnnotationKey (TAB_e1_LENGTH_1)
AnnotationKey (TAB_e1_HTML_TAG_th)
AnnotationKey (TAB_e1_HTML_ANC_TAG_[html])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[body])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[table])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[tbody])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[tr])
AnnotationKey (TAB_e1_HTML_ANC_TAG_[th])
AnnotationKey (TAB_e1_ROW_NUM_[1])
AnnotationKey (TAB_e1_COL_NUM_[0])
AnnotationKey (TAB_e1_ROW_WORDS_[problem])
AnnotationKey (TAB_e1_ROW_WORDS_[cause])
AnnotationKey (TAB_e1_ROW_WORDS_[cost])
AnnotationKey (TAB_e1_ROW_WORDS_[k/w])
AnnotationKey (TAB_e1_ROW_WORDS_[storage])
AnnotationKey (TAB_e1_ROW_WORDS_[storage temperature])
AnnotationKey (TAB_e1_ROW_WORDS_[temperature])
AnnotationKey (TAB_e1_ROW_WORDS_[-55])
AnnotationKey (TAB_e1_ROW_WORDS_[hypochondria])
AnnotationKey (TAB_e1_ROW_WORDS_[fear])
AnnotationKey (TAB_e1_ROW_WORDS_[$])
AnnotationKey (TAB_e1_ROW_WORDS_[$ 100])
AnnotationKey (TAB_e1_ROW_WORDS_[100])
AnnotationKey (TAB_e1_COL_WORDS_[problem])
AnnotationKey (TAB_e1_COL_WORDS_[cause])
AnnotationKey (TAB_e1_COL_WORDS_[cost])
AnnotationKey (TAB_e1_COL_WORDS_[k/w])
AnnotationKey (TAB_e1_COL_WORDS_[storage])
AnnotationKey (TAB_e1_COL_WORDS_[storage temperature])
AnnotationKey (TAB_e1_COL_WORDS_[temperature])
AnnotationKey (TAB_e1_COL_WORDS_[-55])
AnnotationKey (TAB_e1_COL_WORDS_[hypochondria])
AnnotationKey (TAB_e1_COL_WORDS_[fear])
AnnotationKey (TAB_e1_COL_WORDS_[$])
AnnotationKey (TAB_e1_COL_WORDS_[$ 100])
AnnotationKey (TAB_e1_COL_WORDS_[100])
AnnotationKey (TAB_e2_WORD_SEQ_[-55])
AnnotationKey (TAB_e2_LEMMA_SEQ_[-55])
AnnotationKey (TAB_e2_POS_SEQ_[CD])
AnnotationKey (TAB_e2_DEP_SEQ_[ROOT])
AnnotationKey (TAB_e2_W_LEFT_1_[_NUMBER])
AnnotationKey (TAB_e2_W_LEFT_POS_1_[CD])
AnnotationKey (TAB_e2_LENGTH_1)
AnnotationKey (TAB_e2_HTML_TAG_td)
AnnotationKey (TAB_e2_HTML_ANC_TAG_[html])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[body])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[table])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[tbody])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[tr])
AnnotationKey (TAB_e2_HTML_ANC_TAG_[td])
AnnotationKey (TAB_e2_ROW_NUM_[2])
AnnotationKey (TAB_e2_COL_NUM_[1])
AnnotationKey (TAB_e2_ROW_WORDS_[problem])
AnnotationKey (TAB_e2_ROW_WORDS_[cause])
AnnotationKey (TAB_e2_ROW_WORDS_[cost])
AnnotationKey (TAB_e2_ROW_WORDS_[bc546])
AnnotationKey (TAB_e2_ROW_WORDS_[k/w])
AnnotationKey (TAB_e2_ROW_WORDS_[storage])
AnnotationKey (TAB_e2_ROW_WORDS_[storage temperature])
AnnotationKey (TAB_e2_ROW_WORDS_[temperature])
AnnotationKey (TAB_e2_ROW_WORDS_[hypochondria])
AnnotationKey (TAB_e2_ROW_WORDS_[fear])
AnnotationKey (TAB_e2_ROW_WORDS_[$])
AnnotationKey (TAB_e2_ROW_WORDS_[$ 100])
AnnotationKey (TAB_e2_ROW_WORDS_[100])
AnnotationKey (TAB_e2_COL_WORDS_[problem])
AnnotationKey (TAB_e2_COL_WORDS_[cause])
AnnotationKey (TAB_e2_COL_WORDS_[cost])
AnnotationKey (TAB_e2_COL_WORDS_[bc546])
AnnotationKey (TAB_e2_COL_WORDS_[k/w])
AnnotationKey (TAB_e2_COL_WORDS_[storage])
AnnotationKey (TAB_e2_COL_WORDS_[storage temperature])
AnnotationKey (TAB_e2_COL_WORDS_[temperature])
AnnotationKey (TAB_e2_COL_WORDS_[hypochondria])
AnnotationKey (TAB_e2_COL_WORDS_[fear])
AnnotationKey (TAB_e2_COL_WORDS_[$])
AnnotationKey (TAB_e2_COL_WORDS_[$ 100])
AnnotationKey (TAB_e2_COL_WORDS_[100])
AnnotationKey (TAB_SAME_TABLE)
AnnotationKey (TAB_SAME_TABLE_ROW_DIFF_[-1])
AnnotationKey (TAB_SAME_TABLE_COL_DIFF_[-1])
AnnotationKey (TAB_SAME_TABLE_MANHATTAN_DIST_[2])
```

With `infer=True`, it seems that all cells in the table are tagged as being in the same row and the same column. 

A place to start looking may be this function in `lf_helpers.py`
```py
def _get_aligned_phrases(root_phrase, axis, infer=False):
    axis_name = axis + '_num'
    if infer:
        return [phrase for cell in _get_aligned_cells(root_phrase.cell, axis, infer=infer) for phrase in cell.phrases]
    else:
        return [phrase for phrase in getattr(root_phrase, axis).phrases]
```

**Comment by bhancock8** [comment]
Fixed and pushed.

**Comment by lukehsiao** [comment]
I'm still getting this error within the notebook:

```
/home/luke/repos/snorkel/snorkel/lf_helpers.py in _get_aligned_phrases(root_phrase, axis, infer)
    373     if infer:
    374         other_axis = 'row' if axis=='col' else 'col'
--> 375         return [phrase for phrase in _infer_cell(cell, other_axis) for cell in getattr(root_phrase, axis).cells]
    376     else:
    377         return [phrase for phrase in getattr(root_phrase, axis).phrases]

UnboundLocalError: local variable 'cell' referenced before assignment
```

This is what I was getting before and had to change the list comprehension to fix. Does this not cause a problem for you, @bhancock8?
